site_name: NealGuo
copyright: "Copyright © 2025 Neal Guo"

theme:
  name: material
  logo: images/logo.png 
  favicon: images/logo.png   
  palette: 
    # Palette toggle for light mode
        - media: "(prefers-color-scheme)"
          toggle:
            icon: material/link
            name: Switch to light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: indigo
          accent: indigo
          toggle:
            icon: material/weather-sunny
            name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: black
          accent: indigo
          toggle:
            icon: material/weather-night
            name: Switch to system preference
  hero:
    image: docs/images/hero-bg.png
    alt: "Background"
    height: 400px  

  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.footer
    - navigation.indexes
  custom_dir: docs/overrides
nav:
  - Home: index.md
  - CS: 
    - Operating System: 
      - blog/os/Kernel_compilation_experiment.md
  - PI: 
    - CNOOC: blog/oil/CNOOC_history.md
  - About me: aboutme.md 
    # - NealGuo: 
  

plugins:
  - search
  - glightbox
  - mermaid2
     

  # - statistics
  - ai-summary:
      ai_service: "glm"  # "deepseek",or "openai", "gemini", "glm"
      summary_language: "zh"  # or "zh"
      cache_enabled: true
      local_enabled: true
      debug: false
      cache_expire_days: 30
      enabled_folders:
        - blog/os # Process blog folder
        - blog/oil
      # exclude_patterns:
      #   - tags.md # Exclude tags file
  
extra:
  social:
    - icon: fontawesome/brands/weixin
      # link: https://s1.imagehub.cc/images
      link: https://weixin.qq.com/
      name: Wechat
    - icon: fontawesome/brands/github
      link: https://github.com
      name: Github
    - icon: fontawesome/regular/envelope     
      link: https://mail.qq.com
      name: Email
    # link: https://social/@email

  generator: false #是否删除页脚显示“使用 MkDocs 材料制造”
markdown_extensions: #详见https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/ 和 https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - neoteroi.timeline
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.details
  # - pymdownx.blocks
extra_css:
  - styles/extra.css
  